/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.med.calculator.node;

import com.med.calculator.analysis.*;

@SuppressWarnings("nls")
public final class ADivFunc2Factor extends PFactor
{
    private PFactor _factor_;
    private TDiv _div_;
    private PFunc2 _func2_;

    public ADivFunc2Factor()
    {
        // Constructor
    }

    public ADivFunc2Factor(
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PFunc2 _func2_)
    {
        // Constructor
        setFactor(_factor_);

        setDiv(_div_);

        setFunc2(_func2_);

    }

    @Override
    public Object clone()
    {
        return new ADivFunc2Factor(
            cloneNode(this._factor_),
            cloneNode(this._div_),
            cloneNode(this._func2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivFunc2Factor(this);
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PFunc2 getFunc2()
    {
        return this._func2_;
    }

    public void setFunc2(PFunc2 node)
    {
        if(this._func2_ != null)
        {
            this._func2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._func2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factor_)
            + toString(this._div_)
            + toString(this._func2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._func2_ == child)
        {
            this._func2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._func2_ == oldChild)
        {
            setFunc2((PFunc2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
