/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.med.calculator.node;

import com.med.calculator.analysis.*;

@SuppressWarnings("nls")
public final class AExprTerm extends PTerm
{
    private PExprBloc _exprBloc_;

    public AExprTerm()
    {
        // Constructor
    }

    public AExprTerm(
        @SuppressWarnings("hiding") PExprBloc _exprBloc_)
    {
        // Constructor
        setExprBloc(_exprBloc_);

    }

    @Override
    public Object clone()
    {
        return new AExprTerm(
            cloneNode(this._exprBloc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprTerm(this);
    }

    public PExprBloc getExprBloc()
    {
        return this._exprBloc_;
    }

    public void setExprBloc(PExprBloc node)
    {
        if(this._exprBloc_ != null)
        {
            this._exprBloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprBloc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprBloc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprBloc_ == child)
        {
            this._exprBloc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprBloc_ == oldChild)
        {
            setExprBloc((PExprBloc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
