/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.med.calculator.node;

import com.med.calculator.analysis.*;

@SuppressWarnings("nls")
public final class AFunction2Factor extends PFactor
{
    private PFunc2 _func2_;

    public AFunction2Factor()
    {
        // Constructor
    }

    public AFunction2Factor(
        @SuppressWarnings("hiding") PFunc2 _func2_)
    {
        // Constructor
        setFunc2(_func2_);

    }

    @Override
    public Object clone()
    {
        return new AFunction2Factor(
            cloneNode(this._func2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunction2Factor(this);
    }

    public PFunc2 getFunc2()
    {
        return this._func2_;
    }

    public void setFunc2(PFunc2 node)
    {
        if(this._func2_ != null)
        {
            this._func2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._func2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._func2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._func2_ == child)
        {
            this._func2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._func2_ == oldChild)
        {
            setFunc2((PFunc2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
