/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.med.calculator.node;

import com.med.calculator.analysis.*;

@SuppressWarnings("nls")
public final class AFunc extends PFunc
{
    private TFunction _function_;
    private PExprBloc _exprBloc_;

    public AFunc()
    {
        // Constructor
    }

    public AFunc(
        @SuppressWarnings("hiding") TFunction _function_,
        @SuppressWarnings("hiding") PExprBloc _exprBloc_)
    {
        // Constructor
        setFunction(_function_);

        setExprBloc(_exprBloc_);

    }

    @Override
    public Object clone()
    {
        return new AFunc(
            cloneNode(this._function_),
            cloneNode(this._exprBloc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunc(this);
    }

    public TFunction getFunction()
    {
        return this._function_;
    }

    public void setFunction(TFunction node)
    {
        if(this._function_ != null)
        {
            this._function_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._function_ = node;
    }

    public PExprBloc getExprBloc()
    {
        return this._exprBloc_;
    }

    public void setExprBloc(PExprBloc node)
    {
        if(this._exprBloc_ != null)
        {
            this._exprBloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprBloc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._function_)
            + toString(this._exprBloc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._function_ == child)
        {
            this._function_ = null;
            return;
        }

        if(this._exprBloc_ == child)
        {
            this._exprBloc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._function_ == oldChild)
        {
            setFunction((TFunction) newChild);
            return;
        }

        if(this._exprBloc_ == oldChild)
        {
            setExprBloc((PExprBloc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
