/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.med.calculator.node;

import com.med.calculator.analysis.*;

@SuppressWarnings("nls")
public final class AMinusRightExpr extends PRightExpr
{
    private PRightExpr _rightExpr_;
    private PNegExpr _negExpr_;

    public AMinusRightExpr()
    {
        // Constructor
    }

    public AMinusRightExpr(
        @SuppressWarnings("hiding") PRightExpr _rightExpr_,
        @SuppressWarnings("hiding") PNegExpr _negExpr_)
    {
        // Constructor
        setRightExpr(_rightExpr_);

        setNegExpr(_negExpr_);

    }

    @Override
    public Object clone()
    {
        return new AMinusRightExpr(
            cloneNode(this._rightExpr_),
            cloneNode(this._negExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusRightExpr(this);
    }

    public PRightExpr getRightExpr()
    {
        return this._rightExpr_;
    }

    public void setRightExpr(PRightExpr node)
    {
        if(this._rightExpr_ != null)
        {
            this._rightExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightExpr_ = node;
    }

    public PNegExpr getNegExpr()
    {
        return this._negExpr_;
    }

    public void setNegExpr(PNegExpr node)
    {
        if(this._negExpr_ != null)
        {
            this._negExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rightExpr_)
            + toString(this._negExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rightExpr_ == child)
        {
            this._rightExpr_ = null;
            return;
        }

        if(this._negExpr_ == child)
        {
            this._negExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rightExpr_ == oldChild)
        {
            setRightExpr((PRightExpr) newChild);
            return;
        }

        if(this._negExpr_ == oldChild)
        {
            setNegExpr((PNegExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
