/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.med.calculator.node;

import com.med.calculator.analysis.*;

@SuppressWarnings("nls")
public final class AMultFunc2Factor extends PFactor
{
    private PFactor _factor_;
    private TMult _mult_;
    private PFunc2 _func2_;

    public AMultFunc2Factor()
    {
        // Constructor
    }

    public AMultFunc2Factor(
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PFunc2 _func2_)
    {
        // Constructor
        setFactor(_factor_);

        setMult(_mult_);

        setFunc2(_func2_);

    }

    @Override
    public Object clone()
    {
        return new AMultFunc2Factor(
            cloneNode(this._factor_),
            cloneNode(this._mult_),
            cloneNode(this._func2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultFunc2Factor(this);
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PFunc2 getFunc2()
    {
        return this._func2_;
    }

    public void setFunc2(PFunc2 node)
    {
        if(this._func2_ != null)
        {
            this._func2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._func2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factor_)
            + toString(this._mult_)
            + toString(this._func2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._func2_ == child)
        {
            this._func2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._func2_ == oldChild)
        {
            setFunc2((PFunc2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
