/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.med.calculator.node;

import com.med.calculator.analysis.*;

@SuppressWarnings("nls")
public final class ARightExprExpr extends PExpr
{
    private PRightExpr _rightExpr_;

    public ARightExprExpr()
    {
        // Constructor
    }

    public ARightExprExpr(
        @SuppressWarnings("hiding") PRightExpr _rightExpr_)
    {
        // Constructor
        setRightExpr(_rightExpr_);

    }

    @Override
    public Object clone()
    {
        return new ARightExprExpr(
            cloneNode(this._rightExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARightExprExpr(this);
    }

    public PRightExpr getRightExpr()
    {
        return this._rightExpr_;
    }

    public void setRightExpr(PRightExpr node)
    {
        if(this._rightExpr_ != null)
        {
            this._rightExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rightExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rightExpr_ == child)
        {
            this._rightExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rightExpr_ == oldChild)
        {
            setRightExpr((PRightExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
